server:
  port: 8060
  
spring:
  application:
    name: springCloudProducer

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

logging:
  level:
    root: INFO
