server:
  port: 8070

spring:
  application:
    name: springCloudZuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

zuul:
  routes:
    app-hello:
      path: /spring/**
      serviceId: springCloudconsume
