server:
  port: 8090
  
spring:
  application:
    name: springCloudconsume

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka


logging:
  level:
    root: INFO
